kind: pipeline
name: default

steps:
  
- name: Deploy Proxy
  image: ubuntu:bionic
  environment:
    TF_VAR_linode_token:
      from_secret: linode_token
  commands:
  - apt update
  - apt install -y curl unzip openssh-client
  - ssh-keygen -t rsa -b 4096 -C "jmarhee+drone@interiorae.com" -f ~/.ssh/id_rsa -P ""
  - curl --silent --output terraform.zip "https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip"
  - unzip terraform.zip ; rm -f terraform.zip; chmod +x terraform
  - mkdir -p ${HOME}/bin ; export PATH=${PATH}:${HOME}/bin; mv terraform ${HOME}/bin/
  - terraform -v
  - terraform init 
  - terraform validate
  - export TF_VAR_set_osx_proxy=false
  - export TF_VAR_open_browser=false
  - if terraform apply -auto-approve; then "Terraform Applied"; else echo "Apply Failed"; terraform destroy -auto-approve; fi
  - terraform destroy -auto-approve
